version: '3.8'

services:
  # Main LLM Evaluation Platform
  llm-eval-platform:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
      - ./datasets:/app/datasets
      - /var/run/docker.sock:/var/run/docker.sock  # For BigCodeBench execution
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/llm_eval
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - llm-eval-network

  # Redis for session management and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - llm-eval-network

  # PostgreSQL for storing evaluation results (optional)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=llm_eval
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - llm-eval-network

  # Ollama for local model hosting (optional)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - llm-eval-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Uncomment below if you don't have GPU
    # runtime: nvidia

  # BigCodeBench evaluation worker (optional for distributed execution)
  bigcodebench-worker:
    build: .
    command: python -m src.workers.bigcodebench_worker
    volumes:
      - ./results:/app/results
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
      - WORKER_TYPE=bigcodebench
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - llm-eval-network
    deploy:
      replicas: 2

  # Nginx reverse proxy (optional for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - llm-eval-platform
    restart: unless-stopped
    networks:
      - llm-eval-network
    profiles:
      - production

volumes:
  redis_data:
  postgres_data:
  ollama_data:

networks:
  llm-eval-network:
    driver: bridge

# Override configurations for different environments
# Development: docker-compose up
# Production: docker-compose --profile production up
# Minimal: docker-compose up llm-eval-platform redis
